
####################### To fetch from config server ( not using this for nw ) ###########


#localhost ke liye
#spring.config.import=configserver:    not needed
# spring.cloud.config.uri=http://localhost:8888/config-server

# for production on render but to reduce coupling I have hardcoded the properties here so commenting config server connection
#spring.config.import=configserver:    not needed
#spring.cloud.config.uri=https://royal-reserve-config-service.onrender.com/config-server


# yha aur kuch nhi likhenge baaki application.properties will be fetched from the config server







######************* I have given the properties here only (not fetching from config server)  ***************###########

spring.application.name=transaction-api
server.port=8003
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop


#Circular Breaker Properties
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Resilinece4j circuitbreaker Properties
resilience4j.circuitbreaker.instances.asset-management.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.asset-management.event-consumer-buffer-size=10

### this tells the ckt breaker to send 5 req to the half open ckt and check if it is working
resilience4j.circuitbreaker.instances.asset-management.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.asset-management.slidingWindowSize=5

### this tells that if the 50% of the traffic you sending is able to get processed make the half open to closed
resilience4j.circuitbreaker.instances.asset-management.failureRateThreshold=50

### some more props
resilience4j.circuitbreaker.instances.asset-management.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.asset-management.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.asset-management.automaticTransitionFromOpenToHalfOpenEnabled=true

#Resilience4J Timeout And Retry Properties
resilience4j.timelimiter.instances.asset-management.timeout-duration=10s
resilience4j.retry.instances.asset-management.max-attempts=3
resilience4j.retry.instances.asset-management.wait-duration=5s

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=300
spring.redis.jedis.pool.max-active=10
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.min-idle=2