spring.application.name=notification-api
server.port=8004


# ****************** Simple mail properties *********************
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username = duttaarindam902@gmail.com
# this is the app password , not your gmail pwd
spring.mail.password = kvcu dxah gauj gvzr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# *********************************