spring.application.name=account-api
server.port = 8001

#localhost ke liye
spring.config.import=configserver:
spring.cloud.config.uri=http://localhost:8888/config-server

# for production on render but to reduce coupling I have hardcoded the properties here so commentiong cinfig server connection
#spring.config.import=configserver:
#spring.cloud.config.uri=https://royal-reserve-config-service.onrender.com/config-server


# yha aur kuch nhi likhenge baaki application.properties will be fetched from the config server