
####################### To fetch from config server ( not using this for nw ) ###########

#localhost ke liye
#spring.config.import=configserver:    not needed
# spring.cloud.config.uri=http://localhost:8888/config-server

# for production on render but to reduce coupling I have hardcoded the properties here so commenting config server connection
#spring.config.import=configserver:    not needed
#spring.cloud.config.uri=https://royal-reserve-config-service.onrender.com/config-server


# yha aur kuch nhi likhenge baaki application.properties will be fetched from the config server







######************* I have given the properties here only (not fetching from config server)  ***************###########

spring.application.name=account-api
server.port=8001

spring.data.mongodb.uri=mongodb://localhost:27017/account-api-mongo
spring.jpa.hibernate.ddl-auto=create-drop

eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka

#management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
#management.endpoints.web.exposure.include=prometheus
#management.tracing.sampling.probability=1

spring.data.redis.host=localhost
# if it was in a docker compose yml app , then we have to give the container name of the redis not the localhost ( only for local ide run )
spring.data.redis.password=
spring.data.redis.port=6379

spring.cache.redis.time-to-live=300
spring.redis.jedis.pool.max-active=10
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.min-idle=2


######################################## for extensive debug ########################################
#logging.level.root=DEBUG
#debug=true
########################################