spring.application.name=discovery-server
#spring.config.import=configserver:
#spring.cloud.config.uri=http://localhost:8888/config-server
spring.config.import=configserver:http://localhost:8888/config-server
server.port=8761


# Eureka-specific configs for Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false