
####################### To fetch from config server ( not using this for nw ) ###########

#localhost ke liye
#spring.config.import=configserver:    not needed
# spring.cloud.config.uri=http://localhost:8888/config-server

# for production on render but to reduce coupling I have hardcoded the properties here so commenting config server connection
#spring.config.import=configserver:    not needed
#spring.cloud.config.uri=https://royal-reserve-config-service.onrender.com/config-server


# yha aur kuch nhi likhenge baaki application.properties will be fetched from the config server





######************* I have given the properties here only (not fetching from config server)  ***************###########

spring.application.name=discovery-server
server.port=8761

# client services will connect via this url
eureka.instance.hostname=localhost
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Eureka-specific configs for Eureka Server , I have commented to make sure this server is also included in eureka dashboard
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

management.tracing.sampling.probability=1
management.endpoints.web.exposure.include=prometheus